// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Order_Management.Models;

namespace Order_Management.Migrations
{
    [DbContext(typeof(DeliveryTokenDB))]
    [Migration("20201009082422_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Order_Management.Models.TokenDetail", b =>
                {
                    b.Property<int>("Token_Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Customer_Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Pay_Method")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tel_No")
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("Token_Number");

                    b.ToTable("TokenDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
